name: PR Check

on: [pull_request]

jobs:
  build-linkcheck:
    name: Documentation build/linkcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build Sphinx docs
        run: |
          make html linkcheck
